import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState,useEffect } from 'react'
import IngredientCard from '../components/IngredientCard';
import html2canvas from 'html2canvas';
import IngredientsPicker from '../components/IngredientsPicker';

type Ingredient = {
  id:number,
  name:string,
  image:string,
  results:[]
}
export default function Home() {
  const [data,setData] = useState<any>(null);
  const [pending,setPending] = useState(false);
  const [error,setError] = useState('');
  const [input,setInput] = useState('');
  const [selected,setSelected] = useState<any[]>([]);
  console.log('data:',data);
  const fetchData = async (ingredients:string[]) =>{
    setError('');
    setPending(true);
    const response = await fetch('api/hello',{
      method:'POST',
      headers:{
        'Content-Type':'application/json'
      },
      body: JSON.stringify({ingredients})
    });
    const data = await response.json();
    setPending(false);
    if(data.error) return setError(data.error);
    setData(data);
    return data;
  }
  const saveImage = async () =>{
    const div:HTMLElement|null = document.querySelector("#recipe");
    const image = div && await html2canvas(div);
    image && navigator.share(image);
    image && document.querySelector("#test")?.appendChild(image);
    console.log(image);
  }


  return (
    <div className={styles.container} id='test'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {error && <span>{error}</span>}
        <h1 className={styles.title}>
          RecipeGenie 🧞
        </h1>
        <IngredientsPicker callback={fetchData}/>
        {/* <button onClick={()=>fetchData(selected)} disabled={pending}>Wish for Recipe</button>
        <button onClick={()=>saveImage()} disabled={pending}>Share</button> */}

        {data && <div className={styles.recipeContainer} id="recipe">
          <h2>{data.name}</h2>
          <div className={styles.ingredientsContainer}>
            {data.ingredients.map((ingredient:any)=><span>{ingredient} </span>)}
          </div>
          <div className={styles.instructionsContainer}>
            {data.instructions.map((instruction:any,index:number)=><div><span>Step {index+1}</span><p>{instruction}</p></div>)}
          </div>
        </div>}
        
        
    </div>
  )
}
