import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState,useEffect } from 'react'
import html2canvas from 'html2canvas';
import IngredientsPicker from '../components/IngredientsPicker';
import Loading from '../components/Loading';

type Ingredient = {
  id:number,
  name:string,
  image:string,
  results:[]
}
export default function Home() {
  const [data,setData] = useState<any>(null);
  const [pending,setPending] = useState(false);
  const [error,setError] = useState('');

  useEffect(()=>{
    if(!data) return;
    const item = localStorage.getItem('history');
    const history = item ? JSON.parse(item): [];

    localStorage.setItem('history',JSON.stringify([data,...history]));

  },[data]);

  const fetchData = async (recipe:string,ingredients:string[]) =>{
    setError('');
    setPending(true);
    const response = await fetch('api/hello',{
      method:'POST',
      headers:{
        'Content-Type':'application/json'
      },
      body: JSON.stringify({recipe,ingredients})
    });
    const data = await response.json();
    setPending(false);
    if(data.error) return setError(data.error);
    setData(data);
    return data;
  }
  const saveImage = async () =>{
    const div:HTMLElement|null = document.querySelector("#recipe");
    const image = div && await html2canvas(div);
    image && navigator.share(image);
    image && document.querySelector("#test")?.appendChild(image);
    console.log(image);
  }


  return (
    <div className={styles.container} id='test'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1 className={styles.title}>
          RecipeGenie 🧞
        </h1>
        {error && <span>{error}</span>}
        <IngredientsPicker callback={fetchData} className={pending?'shrink':''}/>
        {pending && <Loading/>}

        {data && !pending &&  <div className={styles.recipeContainer} id="recipe">
          <h2>{data.name}</h2>
          <p>
            {data.description}
          </p>
          <h3>Ingredients</h3>
          <div className={styles.ingredientsContainer}>
            {data.ingredients.map((ingredient:any)=><span>{ingredient} </span>)}
          </div>
          <h3>Instructions</h3>
          <div className={styles.instructionsContainer}>
            {data.instructions.map((instruction:any,index:number)=><div><span>Step {index+1}</span><p>{instruction}</p></div>)}
          </div>
        </div>}
        
        
    </div>
  )
}
